name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -e runtime/y5n-runtime-api
          pip install -e runtime/y5n-runtime-engine
          pip install -e runtime/y5n-runtime-transport
          pip install -e runtime/y5n-runtime-store
          pip install -e packs/y5n-packs-system
          pip install -e packs/y5n-packs-ident
          pip install -e sdk/y5n-sdk-python
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest runtime/y5n-runtime-engine/tests \
                runtime/y5n-runtime-store/tests/event \
                runtime/y5n-runtime-store/tests/sequence \
                -x --tb=short
